config/routes.rb
Rails.application.routes.draw do
  resources :work_blocks

  resources :tests

  resources :projects

  resources :homeworks

  resources :courses

  resources :tasks

  get 'welcome/index'

  resources :homes

  devise_for :users
  resources :admins

  resources :members

root to: "welcome#index"

end

app/models/task.rb
# == Schema Information
#
# Table name: tasks
#
#  id             :integer          not null, primary key
#  name           :string(255)
#  created_at     :datetime
#  updated_at     :datetime
#  due_date       :date
#  expected_grade :integer
#  course_id      :integer
#  type           :string(255)
#

class Task < ActiveRecord::Base
  belongs_to :members
  belongs_to :courses
  has_many :work_blocks

  def associated_course
   course = Course.find(course_id)
  end


end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)
    @task.course_id = params[:course_id]
    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:type, :name, :due_date, :expected_grade)
    end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :due_date %><br>
    <%= f.date_field :due_date %>
  </div>

  <div class="field">
    <%= f.label :expected_grade %><br>
    <%= f.number_field :expected_grade %>
  </div>

  <div>
  <%= hidden_field_tag :course_id, params[:course_id] %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing task</h1>

<%= render 'form' %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<h1>Listing tasks</h1>


<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.name %></td>
        <td><%= link_to 'Show', task %></td>
        <td><%= link_to 'Edit', edit_task_path(task) %></td>
        <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Task', new_task_path %>
</br>
</br>
<%= link_to 'Return to Courses', courses_path %>
</br>
</br>

app/views/tasks/new.html.erb
<h1>New task</h1>

<%= render 'form' %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong><%= @task.type %>:</strong>
  <%= @task.name %>
</p>

<p>
  <strong>Course:</strong>
  <%= @task.associated_course.title %>
 </p>

<p>
  <strong>Due Date:</strong>
  <%= @task.due_date %>
 </p>

<p>
  <strong>Expected Grade:</strong>
  <%= @task.expected_grade %>
 </p>

<p>
  <% if @task.work_blocks %>
  <strong>Work Logs:</strong>
         <% @task.work_blocks.each do |work_block| %>
               <li>Start: <%= work_block.start_time %> &nbsp;
		 End: <%= work_block.end_time %>
		 &nbsp;
		 <%= link_to 'Edit', edit_work_block_path(work_block) %> 
	       </li>
         <% end %>
  <% end %>
</br>
 </p>

<%= link_to 'Record Work Log', new_work_block_path(:task_id => @task.id) %> | 
<%= link_to 'Edit Task' , edit_task_path(@task) %>
</br>
</br>
<%= link_to 'Back', course_path(@task.course_id) %> | 
<%= link_to 'Return to Courses', courses_path %> 