config/routes.rb
Rails.application.routes.draw do
  resources :work_blocks

  resources :tests

  resources :projects

  resources :homeworks

  resources :courses

  resources :tasks

  get 'welcome/index'

  resources :homes

  devise_for :users
  resources :admins

  resources :members

root to: "welcome#index"

end

app/models/project.rb
# == Schema Information
#
# Table name: tasks
#
#  id             :integer          not null, primary key
#  name           :string(255)
#  created_at     :datetime
#  updated_at     :datetime
#  due_date       :date
#  expected_grade :integer
#  course_id      :integer
#  type           :string(255)
#

class Project < Task
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)
    @project.course_id = params[:course_id]
    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:type, :name, :due_date, :expected_grade)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :due_date %><br>
    <%= f.date_field :due_date %>
  </div>

  <div class="field">
    <%= f.label :expected_grade %><br>
    <%= f.number_field :expected_grade %>
  </div>

  <div>
  <%= hidden_field_tag :course_id, params[:course_id] %>
  </div>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<h1>Listing projects</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= link_to 'Show', project %></td>
        <td><%= link_to 'Edit', edit_project_path(project) %></td>
        <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Project', new_project_path %>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>


<p>
  <strong>Name:</strong>
  <%= @project.name %>
</p>

<p>
  <strong>Course:</strong>
  <%= @project.associated_course.title %>
 </p>

<p>
  <strong>Due Date:</strong>
  <%= @project.due_date %>
 </p>

<p>
  <strong>Expected Grade:</strong>
  <%= @project.expected_grade %>
 </p>

<p>
<% if @project.work_blocks %>
  <strong>Work Logs:</strong>
         <% @project.work_blocks.each do |work_block| %>
               <li>Start: <%= work_block.start_time %> &nbsp;
		  End: <%= work_block.end_time %>
		  &nbsp;
		  <%= link_to 'Edit', edit_work_block_path(work_block) %> 
		         </li>
         <% end %>
  <% end %>
</br>

 </p>

<%= link_to 'Record Work Log', new_work_block_path(:task_id => @project.id) %> | <%= link_to 'Edit Task' , edit_task_path(@project) %>
</br>
</br>
<%= link_to 'Back', course_path(@project.course_id) %> | 
<%= link_to 'Return to Courses', courses_path %>
</br>