config/routes.rb
Rails.application.routes.draw do
  resources :work_blocks

  resources :tests

  resources :projects

  resources :homeworks

  resources :courses

  resources :tasks

  get 'welcome/index'

  resources :homes

  devise_for :users
  resources :admins

  resources :members

root to: "welcome#index"

end

app/models/homework.rb
# == Schema Information
#
# Table name: tasks
#
#  id             :integer          not null, primary key
#  name           :string(255)
#  created_at     :datetime
#  updated_at     :datetime
#  due_date       :date
#  expected_grade :integer
#  course_id      :integer
#  type           :string(255)
#

class Homework < Task
end

app/controllers/homeworks_controller.rb
class HomeworksController < ApplicationController
  before_action :set_homework, only: [:show, :edit, :update, :destroy]

  # GET /homeworks
  # GET /homeworks.json
  def index
    @homeworks = Homework.all
  end

  # GET /homeworks/1
  # GET /homeworks/1.json
  def show
  end

  # GET /homeworks/new
  def new
    @homework = Homework.new
  end

  # GET /homeworks/1/edit
  def edit
  end

  # POST /homeworks
  # POST /homeworks.json
  def create
    @homework = Homework.new(homework_params)
    @homework.course_id = params[:course_id]
    respond_to do |format|
      if @homework.save
        format.html { redirect_to @homework, notice: 'Homework was successfully created.' }
        format.json { render :show, status: :created, location: @homework }
      else
        format.html { render :new }
        format.json { render json: @homework.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /homeworks/1
  # PATCH/PUT /homeworks/1.json
  def update
    respond_to do |format|
      if @homework.update(homework_params)
        format.html { redirect_to @homework, notice: 'Homework was successfully updated.' }
        format.json { render :show, status: :ok, location: @homework }
      else
        format.html { render :edit }
        format.json { render json: @homework.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /homeworks/1
  # DELETE /homeworks/1.json
  def destroy
    @homework.destroy
    respond_to do |format|
      format.html { redirect_to homeworks_url, notice: 'Homework was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_homework
      @homework = Homework.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def homework_params
      params.require(:homework).permit(:type, :name, :due_date, :expected_grade)
    end
end

app/helpers/homeworks_helper.rb
module HomeworksHelper
end

app/views/homeworks/_form.html.erb
<%= form_for(@homework) do |f| %>
  <% if @homework.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@homework.errors.count, "error") %> prohibited this homework from being saved:</h2>

      <ul>
      <% @homework.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

 <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :due_date %><br>
    <%= f.date_field :due_date %>
  </div>

  <div class="field">
    <%= f.label :expected_grade %><br>
    <%= f.number_field :expected_grade %>
  </div>

  <div>
  <%= hidden_field_tag :course_id, params[:course_id] %>
  </div>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/homeworks/edit.html.erb
<h1>Editing homework</h1>

<%= render 'form' %>

<%= link_to 'Show', @homework %> |
<%= link_to 'Back', homeworks_path %>

app/views/homeworks/index.html.erb
<h1>Listing homeworks</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @homeworks.each do |homework| %>
      <tr>
        <td><%= link_to 'Show', homework %></td>
        <td><%= link_to 'Edit', edit_homework_path(homework) %></td>
        <td><%= link_to 'Destroy', homework, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Homework', new_homework_path %>

app/views/homeworks/new.html.erb
<h1>New homework</h1>

<%= render 'form' %>

<%= link_to 'Back', homeworks_path %>

app/views/homeworks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @homework.name %>
</p>

<p>
  <strong>Course:</strong>
  <%= @homework.associated_course.title %>
 </p>

<p>
  <strong>Due Date:</strong>
  <%= @homework.due_date %>
 </p>

<p>
  <strong>Expected Grade:</strong>
  <%= @homework.expected_grade %>
 </p>

<p>
  <% if @homework.work_blocks %>
  <strong>Work Logs:</strong>
         <% @homework.work_blocks.each do |work_block| %>
               <li>Start: <%= work_block.start_time %> &nbsp;
		  End: <%= work_block.end_time %>
		  &nbsp;
		  <%= link_to 'Edit', edit_work_block_path(work_block) %> 
	        </li>
         <% end %>
  <% end %>
</br>

 </p>

<%= link_to 'Record Work Log', new_work_block_path(:task_id => @homework.id) %>
</br>
</br>
<%= link_to 'Back', course_path(@homework.course_id) %> | 
<%= link_to 'Return to Courses', courses_path %> 
</br>